name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Run acceptance tests
      run: npm test -- --group=acceptance

    - name: Run e2e tests
      run: npm test -- --group=e2e

    - name: Run functional tests
      run: npm test -- --group=functional

    - name: Run integration tests
      run: npm test -- --group=integration

    - name: Run performance tests
      run: npm test -- --group=performance

    - name: Run smoke tests
      run: npm test -- --group=smoke

    - name: Upload HTML test report
      if: success()
      uses: actions/upload-artifact@v3
      with:
        name: html-reports
        path: html-report/report.html